before_script:
  - apt-get install -y phpunit

# PHP 5.5
php:5.5:
  image: bobey/docker-gitlab-ci-runner-php5.5
  script:
    - echo "Running PHPUnit Tests"
    - phpunit -c tests

# PHP 5.6
php:5.6:
  image: bobey/docker-gitlab-ci-runner-php5.6
  script:
    - echo "Running PHPUnit Tests"
    - phpunit -c tests
