addons:
    code_climate:
        repo_token: ecd1af07b8276c147bb918eb8e280bd4d8edfe4944fda4f0e59217f236624116
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
script:
  - echo "Running PHPUnit Tests"
  - phpunit tests/*
